name: Run Jest Tests # Назва пайплайну

on:
  push:
    branches: [main] # Запускати тести при пуші в main
  pull_request:
    branches: [main] # Запускати тести при PR у main
  schedule:
    - cron: "0 6 * * *" # Запускати щодня о 6 ранку (UTC)

jobs:
  test:
    runs-on: ubuntu-latest # Віртуальна машина для запуску

    steps:
      - name: Checkout repository # Клонування репозиторію
        uses: actions/checkout@v3

      - name: Set up Node.js # Встановлення Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies # Встановлення npm пакетів
        run: npm install

      - name: Run Jest tests # Запуск Jest тестів
        run: npm test

      - name: Upload test results (optional)
  if: always()
  uses: actions/upload-artifact@v4
  with:
    name: jest-results
    path: jest-results.xml
